apiVersion: v1
kind: Service
metadata:
  name: divs-loadbalancer
  labels:
    app: appversion-2.0

spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: appversion-2.0
