apiVersion: batch/v1
kind: Job
metadata:
  name: pi-job
spec:
  completions: 5
  ttlSecondsAfterFinished: 10
  template:
    metadata:
      name: pi-pod
    spec:
      containers:
      - name: pi-container
        image: perl:5.34.0
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4