
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: divya-persistentvolumeclaim
spec:
  storageClassName: custom-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi