
apiVersion: v1
kind: PersistentVolume
metadata:
  name: divya-persistentvolume

spec:
  storageClassName: custom-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/tmp"