apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-persistnt-vol

spec:
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain

  capacity:
    storage: 1Gi

  accessModes:
    - ReadWriteOnce
    
  hostPath:
    path: /var/tmp