apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: redis

spec:
  replicas: 10 # upgrade from 15 to 10
  selector:
    matchLabels:
      app: redis
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 # upgrade from 2 to 1
      maxUnavailable: 2 # upgrade to 2 to 0
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis-container
          image: redis:7.4.1 #Upgrade from 5.0 to 6.0 --> 6.0.16 --> 6.2.6 --> 7.4.1
