kind: Deployment
apiVersion: apps/v1
metadata:
  name: redis
spec:
  replicas: 10
  selector:
    matchLabels:
      name: redis
  template:
    metadata:
      labels:
        name: redis
    spec:
      containers:
        - name: redis
          image: redis:6.2
          resources:
            requests:
              memory: 200Mi # insufficient memory for 700Mi
              cpu: 100m # insufficient CPU for 900m
            limits:
              memory: 400Mi
              cpu: 1
