
# divsnginx-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: divsnginx-pod
  namespace: default
  labels:
    run: nginx-pod
spec:
  containers:
  - image: nginx:stable-perl
    name: nginx-pod-container
    env:
    - name: "GREETINGS"
      value: "I'm doing great, thank you"
    - name: "GREAT_TIME"
      value: "I sure did, thanks for asking"

