apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: divs-liveness-http-pod
spec:
  containers:
  - name: divs-liveness-container
    image: registry.k8s.io/e2e-test-images/agnhost:2.40
    args:
    - liveness
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
        httpHeaders:
        - name: Custom-Header
          value: Awesome
      initialDelaySeconds: 3
      periodSeconds: 3